# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "bucket-to-test-if-things-work"
    encrypt = true
    key     = "./coupon-system.tfstate"
    region  = "us-east-1"
  }
}
